judul_komentar = [
        "Komentar 1",
        "Komentar 2",
        "UNITY UNY",
        "INVENTION UNUD",
        "SCREEN UNTAN",
        "CTF TNI AD",
        "GUBUFEST",
        "LOMBA DI UNISSULA",
        "MICROSOFT IMAGINE CUP",
        "DINACOM 2018",
        "FIND IT UGM",
        "TELKOM HACKATHON 2018",
        "MAGE ITS",
        "SAYEMBARA DESAIN LOGO KBI",
        "AAJI HACKATHON",
        "FIT COMPETITION UKSW",
        "TECHCOMFEST 2018",
        "ITFEST USU"
];